=== anasteish22/task2/src/main/resources/plants.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.anastasia.task2/plants"
        xmlns:tns="http://by.anastasia.task2/plants"
        elementFormDefault="qualified">

    <element name="plants">
        <complexType>
            <sequence>
                <element name="plant" type="tns:plant" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="plant" type="tns:plant" abstract="true"/>
    <element name="monocotyledon" type="tns:monocotyledon" substitutionGroup="tns:plant"/>
    <element name="dicotyledon" type="tns:dicotyledon" substitutionGroup="tns:plant"/>

    <complexType name="plant">
        <sequence>
            <element name="soil" type="string"/>
            <element name="origin" type="tns:origin"/>
            <element name="stemColor" type="string"/>
            <element name="leafColor" type="string"/>
            <element name="size" type="positiveInteger"/>
            <element name="temperature" type="tns:temperature"/>
            <element name="photophilous" type="boolean"/>
            <element name="multiplying" type="tns:multiplying"/>
        </sequence>
        <attribute name="id" type="tns:id" use="required"/>
        <attribute name="name" type="string"/>
    </complexType>

    <complexType name="monocotyledon">
        <complexContent>
            <extension base="tns:plant">
                <sequence>
                    <element name="isFlowerForming" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="dicotyledon">
        <complexContent>
            <extension base="tns:plant">
                <sequence>
                    <element name="calyxType" type="tns:calyxType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="id">
        <restriction base="ID">
            <pattern value="[A-Z]\\d{6}"/>
        </restriction>
    </simpleType>
    <simpleType name="origin">
        <restriction base="string">
            <enumeration value="Europe"/>
            <enumeration value="Asia"/>
            <enumeration value="Africa"/>
            <enumeration value="Australia"/>
            <enumeration value="South America"/>
            <enumeration value="North America"/>
        </restriction>
    </simpleType>
    <simpleType name="temperature">
        <restriction base="integer">
            <minInclusive value="-273"/>
            <maxInclusive value="56"/>
        </restriction>
    </simpleType>
    <simpleType name="multiplying">
        <restriction base="string">
            <enumeration value="cuttings"/>
            <enumeration value="layering"/>
            <enumeration value="seeds"/>
        </restriction>
    </simpleType>
    <simpleType name="calyxType">
        <restriction base="string">
            <enumeration value="segmented"/>
            <enumeration value="united segments"/>
        </restriction>
    </simpleType>
</schema>

=== anasteish22/task2/xml/plants.xml
<?xml version="1.0" encoding="UTF-8" ?>
<plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://by.anastasia.task2/plants"
        xsi:schemaLocation="http://by.anastasia.task2/plants plants.xsd">

    <dicotyledon plantId="R100001" plantingDate="2023-04-16" name="Rosa chinesis">
        <soil>derno-podzolic</soil>
        <origin>Asia</origin>
        <stemColor>green</stemColor>
        <leafColor>green</leafColor>
        <size>150</size>
        <temperature>20</temperature>
        <photophilous>true</photophilous>
        <multiplying>cuttings</multiplying>
        <calyxType>segmented</calyxType>
    </dicotyledon>
    <monocotyledon plantId="N100002" plantingDate="2022-03-23" name="Nymphaea">
        <soil>loamy</soil>
        <origin>Europe</origin>
        <stemColor>green</stemColor>
        <leafColor>green</leafColor>
        <size>50</size>
        <temperature>4</temperature>
        <photophilous>true</photophilous>
        <multiplying>layering</multiplying>
        <isFlowerForming>true</isFlowerForming>
    </monocotyledon>
    <monocotyledon plantId="H100003" plantingDate="2023-06-04" name="Hosta">
        <soil>loamy</soil>
        <origin>Asia</origin>
        <stemColor>green</stemColor>
        <leafColor>green</leafColor>
        <size>40</size>
        <temperature>15</temperature>
        <photophilous>false</photophilous>
        <multiplying>seeds</multiplying>
        <isFlowerForming>true</isFlowerForming>
    </monocotyledon>
    <dicotyledon plantId="B100004" plantingDate="2021-09-05" name="Barbaris">
        <soil>loamy</soil>
        <origin>North America</origin>
        <stemColor>red</stemColor>
        <leafColor>red-purple</leafColor>
        <size>180</size>
        <temperature>5</temperature>
        <photophilous>true</photophilous>
        <multiplying>cuttings</multiplying>
        <calyxType>segmented</calyxType>
    </dicotyledon>
    <dicotyledon plantId="S100005" plantingDate="2022-05-05" name="Strawberry">
        <soil>loamy</soil>
        <origin>South America</origin>
        <stemColor>green</stemColor>
        <leafColor>green</leafColor>
        <size>15</size>
        <temperature>24</temperature>
        <photophilous>true</photophilous>
        <multiplying>hybridization</multiplying>
        <calyxType>segmented</calyxType>
    </dicotyledon>
    <dicotyledon plantId="C100006" plantingDate="2020-03-27" name="Cherry">
        <soil>loamy</soil>
        <origin>Europe</origin>
        <stemColor>brown</stemColor>
        <leafColor>green</leafColor>
        <size>220</size>
        <temperature>7</temperature>
        <photophilous>true</photophilous>
        <multiplying>layering</multiplying>
        <calyxType>segmented</calyxType>
    </dicotyledon>
    <dicotyledon plantId="S100007" plantingDate="2018-04-13" name="Sakura">
        <soil>loamy</soil>
        <origin>Asia</origin>
        <stemColor>brown</stemColor>
        <leafColor>green</leafColor>
        <size>350</size>
        <temperature>20</temperature>
        <photophilous>true</photophilous>
        <multiplying>cuttings</multiplying>
        <calyxType>united segments</calyxType>
    </dicotyledon>
    <monocotyledon plantId="P100008" plantingDate="2017-08-04" name="Palm">
        <soil>humus</soil>
        <origin>Africa</origin>
        <stemColor>brown</stemColor>
        <leafColor>green</leafColor>
        <size>270</size>
        <temperature>22</temperature>
        <photophilous>true</photophilous>
        <multiplying>seeds</multiplying>
        <isFlowerForming>false</isFlowerForming>
    </monocotyledon>
</plants>

=== anasteish22/task2/src/main/resources/plants.xml
<?xml version="1.0" encoding="UTF-8" ?>
<plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://by.anastasia.task2/plants"
        xsi:schemaLocation="http://by.anastasia.task2/plants plants.xsd">

    <dicotyledon id="R100002" name="Rosa chinesis">
        <soil>derno-podzolic</soil>
        <origin>Asia</origin>
        <stemColor>green</stemColor>
        <leafColor>green</leafColor>
        <size>150</size>
        <temperature>20</temperature>
        <photophilous>true</photophilous>
        <multiplying>cuttings</multiplying>
        <calyxType>segmented</calyxType>
    </dicotyledon>
    <monocotyledon id="N100003" name="Nymphaea">
        <soil>loamy</soil>
        <origin>Europe</origin>
        <stemColor>green</stemColor>
        <leafColor>green</leafColor>
        <size>50</size>
        <temperature>4</temperature>
        <photophilous>true</photophilous>
        <multiplying>layering</multiplying>
        <isFlowerForming>true</isFlowerForming>
    </monocotyledon>
    <monocotyledon id="H100004" name="Hosta">
        <soil>loamy</soil>
        <origin>Asia</origin>
        <stemColor>green</stemColor>
        <leafColor>green</leafColor>
        <size>40</size>
        <temperature>15</temperature>
        <photophilous>false</photophilous>
        <multiplying>seeds</multiplying>
        <isFlowerForming>true</isFlowerForming>
    </monocotyledon>
    <dicotyledon id="B100005" name="Barbaris">
        <soil>loamy</soil>
        <origin>North America</origin>
        <stemColor>red</stemColor>
        <leafColor>red-purple</leafColor>
        <size>180</size>
        <temperature>5</temperature>
        <photophilous>true</photophilous>
        <multiplying>cuttings</multiplying>
        <calyxType>segmented</calyxType>
    </dicotyledon>
</plants>
